# Jupyter Book settings

title: Jupyter & book
author: Thierry Parmentelat
logo: media/jupyter-book-logo-wide.svg

repository:
  url: https://github.com/parmentelat/jupyterlab-tpt
  branch: main
  path_to_book: examples

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes

only_build_toc_files: true

exclude_patterns:
  - "**/.teacher/*"

execute:
  execute_notebooks: cache
  exclude_patterns:
    - "**/*-corrige*"
    - "**/.teacher/*"
    - "**/snake*.py"

parse:
  myst_enable_extensions:
    - html_image    # for raw <img> tags in markdown
    - dollarmath    # for mathjax
    - strikethrough

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    html_show_copyright: false
    # not quite convincing but...
    html_extra_path:
      - 'media'
      # not actually needed, but also we don't expose any content to jlite
      # - 'lite'
    jupyterlite_dir: .
    # to get the corrections to embed in the jlite folder
    jupyterlite_contents:
      - ../modules/corrections
      - data
    nb_ipywidgets_js:
        # Load RequireJS, used by the IPywidgets for dependency management
        "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js": 
            "integrity": "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
            "crossorigin": "anonymous"
        # Load IPywidgets bundle for embedding.
        "https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@*/dist/embed-amd.js":
            "data-jupyter-widgets-cdn": "https://cdn.jsdelivr.net/npm/"
            "crossorigin": "anonymous"

  extra_extensions:
    - sphinxcontrib.video
    - jupyterlite_sphinx
    - sphinx_exercise
    # for mermaid diagrams, see also
    # https://opencomputinglab.github.io/SubjectMatterNotebooks/diagram/sphinx-diagrammers.html
    # https://blog.ouseful.info/2021/11/02/previewing-sphinx-and-jupyter-book-rendered-mermaid-and-wavedrom-diagrams-in-vs-code/
    # - myst_parser
    - sphinxcontrib.mermaid

    # looks like we're going to need this if/when it gets released
    # https://github.com/mgaitan/sphinxcontrib-mermaid/pull/76
    # - sphinxcontrib.mermaid_inheritance
    #
    # other diagraming tools that may turn out useful
    # - sphinxcontrib.wavedrom
    # - sphinxcontrib.plantuml
    # - sphinxcontrib.tikz
    # - sphinxcontrib.blockdiag

