
include Makefile.book2
include Makefile.style2
include Makefile.prune
NOTEBOOKS := $(wildcard [0-9]*.md)
NBNORMFLAGS = -t 1 -L Licence --license-delete -S _static/style --style-delete
include Makefile.norm
